// ActionTypes.js
export const ActionTypes = {
  SET_URL_VISITAS: "SET_URL_VISITAS",
  SET_URL_QUIZ: "SET_URL_QUIZ",
  SET_EXIBIR: "SET_EXIBIR",
  SET_SHOW_CLOCK: "SET_SHOW_CLOCK",
  SET_LIMIT_TIME: "SET_LIMIT_TIME",
  SET_TIME_REMAIN: "SET_TIME_REMAIN",
  SET_IS_FULL_SCREEN: "SET_IS_FULL_SCREEN",
  SET_ALIGN_TO_CENTER: "SET_ALIGN_TO_CENTER",
  SET_SHOW_QR_CODE: "SET_SHOW_QR_CODE",
  SET_SHOW_VISITAS: "SET_SHOW_VISITAS",
  SET_TEXTO_LICAO_ACABOU: "SET_TEXTO_LICAO_ACABOU",
  SET_AUDIO_ENABLE: "SET_AUDIO_ENABLE",
  SET_PLAY_1_MIN: "SET_PLAY_1_MIN",
  SET_PLAY_5_MIN: "SET_PLAY_5_MIN",
  SET_FILE_1_MIN: "SET_FILE_1_MIN",
  SET_FILE_5_MIN: "SET_FILE_5_MIN",
};
